server:
  port: 8080

spring:
  application:
    name: DASHBOARD
  datasource:
    url: jdbc:h2:file:./data/dashboard
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

